version: '3'

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
  mysql:


services:
  blog:
    build: .
    depends_on:
      - database
      - netdata
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    environment:
      - NODE_ENV=production
      - DD_BLOG_ENABLED=true
      - DD_CMS_ENABLED=true
      - DD_CLOUDCENTER_ENABLED=true
      - DD_BLOG_PORT=3000
      - DD_CMS_PORT=3001
      - DD_CLOUDCENTER_PORT=3002
      - DD_DBNAME=derdomeeBlog
      - DD_DBUSER=databaseuser
      - DD_DBPASS=databasepassword
      - DD_DBHOST=database
    container_name: blog
  database:
    image: mysql:5.7
    container_name: database
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=derdomeeBlog
      - MYSQL_USER=databaseuser
      - MYSQL_PASSWORD=databasepassword
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: localhost
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/paswd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
