# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Use Node.js 18
        uses: actions/setup-node@2a017f350dbf6c4b6bb4508cc83809719115162e
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Use Node.js 18
        uses: actions/setup-node@2a017f350dbf6c4b6bb4508cc83809719115162e
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm test

  build:
    runs-on: ubuntu-latest
    needs: ["test", "lint"]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Use Node.js 18
        uses: actions/setup-node@2a017f350dbf6c4b6bb4508cc83809719115162e
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npm run build
